// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0v8DZ29QFlMU0mw8GZGvImk9EgKcQNA',
    appId: '1:771455438786:web:e558a0cdab403ed2b9d05b',
    messagingSenderId: '771455438786',
    projectId: 'learning-app-fbfde',
    authDomain: 'learning-app-fbfde.firebaseapp.com',
    storageBucket: 'learning-app-fbfde.firebasestorage.app',
    measurementId: 'G-M343T6DCXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIpi8FfP18Tnbl52U_6ZOjRYIl6VroD4o',
    appId: '1:771455438786:android:4094d6320b199eb6b9d05b',
    messagingSenderId: '771455438786',
    projectId: 'learning-app-fbfde',
    storageBucket: 'learning-app-fbfde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvtenN74GpgBJLmMjAgUTO7uA57EO8CU',
    appId: '1:771455438786:ios:1d0c9972d9a2a753b9d05b',
    messagingSenderId: '771455438786',
    projectId: 'learning-app-fbfde',
    storageBucket: 'learning-app-fbfde.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyvtenN74GpgBJLmMjAgUTO7uA57EO8CU',
    appId: '1:771455438786:ios:1d0c9972d9a2a753b9d05b',
    messagingSenderId: '771455438786',
    projectId: 'learning-app-fbfde',
    storageBucket: 'learning-app-fbfde.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0v8DZ29QFlMU0mw8GZGvImk9EgKcQNA',
    appId: '1:771455438786:web:f13329d326d4d903b9d05b',
    messagingSenderId: '771455438786',
    projectId: 'learning-app-fbfde',
    authDomain: 'learning-app-fbfde.firebaseapp.com',
    storageBucket: 'learning-app-fbfde.firebasestorage.app',
    measurementId: 'G-DBV6G2Y29R',
  );
}
